language: node_js

node_js:
    - stable

install:
    - yarn

jobs:
    include:
        - stage: Tests
          script: yarn test
        - stage: Build App
          script: yarn build:app

deploy:
    provider: pages
    skip-cleanup: true
    local_dir: public
    github-token: $GITHUB_TOKEN
    keep-history: true
    target_branch: gh-pages
    on:
        branch: master
