language: node_js

node_js:
    - stable

install:
    - yarn

jobs:
    include:
        - stage: Tests
          script: yarn test

deploy:
    provider: pages:git
    token: $GITHUB_TOKEN
    keep_history: true
    target_branch: gh-pages
    on:
        branch: master
